

export const softwareProducts = [
    {
        id: 1,
        shortSrc: 'https://mailmeteor.com/logos/assets/PNG/Microsoft_Logo_512px.png',
        longSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Microsoft_logo_%282012%29.svg/1280px-Microsoft_logo_%282012%29.svg.png',
        title: 'NCE Microsoft 365 Business',
        vendor: 'Microsoft',
        tag: 'Free trial',
        shortDesc: 'Build your future with Microsoft 365',
        longDesc: 'Help people and teams do their best work with the apps and experiences they rely on everyday to connect, collaborate, and get work done from anywhere. Help people and teams do their best work with the apps and experiences they rely on everyday to connect, collaborate, and get work done from anywhere. Help people and teams do their best work with the apps and experiences they rely on everyday to connect, collaborate, and get work done from anywhere.',
        price: 'From CA$4.10',
        period: 'user/month',
    },
    {
        id: 2,
        shortSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Adobe_Acrobat_DC_logo_2020.svg/1200px-Adobe_Acrobat_DC_logo_2020.svg.png',
        longSrc: 'https://www.adobe.com/content/dam/dx-dc/us/en/acrobat/gen-ai/adobe-acrobat-horizontal%20black-logo.png.img.png',
        title: "Adobe Acrobat Pro for Teams",
        vendor: 'Adobe',
        tag: '',
        shortDesc: "Discover all the things your PDF can do.",
        longDesc: "Adobe Acrobat DC helps you keep your business moving. Convert, edit, share, and sign PDFs. It keeps you connected to your team with simple workflows across desktop, mobile, and web — no matter where you're working. It keeps you connected to your team with simple workflows across desktop, mobile, and web — no matter where you're working. It keeps you connected to your team with simple workflows across desktop, mobile, and web — no matter where you're working. It keeps you connected to your team with simple workflows across desktop, mobile, and web — no matter where you're working.",
        price: 'From CA$4.10',
        period: 'user/month',
    },
    {
        id: 3,
        shortSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Dropbox_Icon.svg/2202px-Dropbox_Icon.svg.png',
        longSrc: 'https://logodownload.org/wp-content/uploads/2021/02/dropbox-logo.png',
        title: "Dropbox Business",
        vendor: 'Dropbox',
        tag: 'Free trial',
        shortDesc: "Everything your business needs to work efficiently.",
        longDesc: "Dropbox Business lets your team bring work anywhere, syncing their important files across all their devices. Powerful admin tools help you stay on top of your account and take control of your organization's information. Shared folders and links help keep everyone up to date, effortlessly. With Dropbox, team members can work together like they're sitting right next to each other — even when they're halfway around the world.",
        price: 'From CA$4.10',
        period: 'user/month',
    },
    {
        id: 4,
        shortSrc: 'https://mailmeteor.com/logos/assets/PNG/Microsoft_Logo_512px.png',
        longSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Microsoft_logo_%282012%29.svg/1280px-Microsoft_logo_%282012%29.svg.png',
        title: 'NCE Microsoft 365 Business',
        vendor: 'Microsoft',
        tag: 'Free trial',
        shortDesc: 'Build your future with Microsoft 365',
        longDesc: 'Help people and teams do their best work with the apps and experiences they rely on everyday to connect, collaborate, and get work done from anywhere. Help people and teams do their best work with the apps and experiences they rely on everyday to connect, collaborate, and get work done from anywhere. Help people and teams do their best work with the apps and experiences they rely on everyday to connect, collaborate, and get work done from anywhere.',
        price: 'From CA$4.10',
        period: 'user/month',
    },
    {
        id: 5,
        shortSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Adobe_Acrobat_DC_logo_2020.svg/1200px-Adobe_Acrobat_DC_logo_2020.svg.png',
        longSrc: 'https://www.adobe.com/content/dam/dx-dc/us/en/acrobat/gen-ai/adobe-acrobat-horizontal%20black-logo.png.img.png',
        title: "Adobe Acrobat Pro for Teams",
        vendor: 'Adobe',
        tag: '',
        shortDesc: "Discover all the things your PDF can do.",
        longDesc: "Adobe Acrobat DC helps you keep your business moving. Convert, edit, share, and sign PDFs. It keeps you connected to your team with simple workflows across desktop, mobile, and web — no matter where you're working. It keeps you connected to your team with simple workflows across desktop, mobile, and web — no matter where you're working. It keeps you connected to your team with simple workflows across desktop, mobile, and web — no matter where you're working. It keeps you connected to your team with simple workflows across desktop, mobile, and web — no matter where you're working.",
        price: 'From CA$4.10',
        period: 'user/month',
    },
    {
        id: 6,
        shortSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Dropbox_Icon.svg/2202px-Dropbox_Icon.svg.png',
        longSrc: 'https://logodownload.org/wp-content/uploads/2021/02/dropbox-logo.png',
        title: "Dropbox Business",
        vendor: 'Dropbox',
        tag: 'Free trial',
        shortDesc: "Everything your business needs to work efficiently.",
        longDesc: "Dropbox Business lets your team bring work anywhere, syncing their important files across all their devices. Powerful admin tools help you stay on top of your account and take control of your organization's information. Shared folders and links help keep everyone up to date, effortlessly. With Dropbox, team members can work together like they're sitting right next to each other — even when they're halfway around the world.",
        price: 'From CA$4.10',
        period: 'user/month',
    },
    {
        id: 7,
        shortSrc: 'https://mailmeteor.com/logos/assets/PNG/Microsoft_Logo_512px.png',
        longSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Microsoft_logo_%282012%29.svg/1280px-Microsoft_logo_%282012%29.svg.png',
        title: 'NCE Microsoft 365 Business',
        vendor: 'Microsoft',
        tag: 'Free trial',
        shortDesc: 'Build your future with Microsoft 365',
        longDesc: 'Help people and teams do their best work with the apps and experiences they rely on everyday to connect, collaborate, and get work done from anywhere. Help people and teams do their best work with the apps and experiences they rely on everyday to connect, collaborate, and get work done from anywhere. Help people and teams do their best work with the apps and experiences they rely on everyday to connect, collaborate, and get work done from anywhere.',
        price: 'From CA$4.10',
        period: 'user/month',
    },
    {
        id: 8,
        shortSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Adobe_Acrobat_DC_logo_2020.svg/1200px-Adobe_Acrobat_DC_logo_2020.svg.png',
        longSrc: 'https://www.adobe.com/content/dam/dx-dc/us/en/acrobat/gen-ai/adobe-acrobat-horizontal%20black-logo.png.img.png',
        title: "Adobe Acrobat Pro for Teams",
        vendor: 'Adobe',
        tag: '',
        shortDesc: "Discover all the things your PDF can do.",
        longDesc: "Adobe Acrobat DC helps you keep your business moving. Convert, edit, share, and sign PDFs. It keeps you connected to your team with simple workflows across desktop, mobile, and web — no matter where you're working. It keeps you connected to your team with simple workflows across desktop, mobile, and web — no matter where you're working. It keeps you connected to your team with simple workflows across desktop, mobile, and web — no matter where you're working. It keeps you connected to your team with simple workflows across desktop, mobile, and web — no matter where you're working.",
        price: 'From CA$4.10',
        period: 'user/month',
    },
    {
        id: 9,
        shortSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Dropbox_Icon.svg/2202px-Dropbox_Icon.svg.png',
        longSrc: 'https://logodownload.org/wp-content/uploads/2021/02/dropbox-logo.png',
        title: "Dropbox Business",
        vendor: 'Dropbox',
        tag: 'Free trial',
        shortDesc: "Everything your business needs to work efficiently.",
        longDesc: "Dropbox Business lets your team bring work anywhere, syncing their important files across all their devices. Powerful admin tools help you stay on top of your account and take control of your organization's information. Shared folders and links help keep everyone up to date, effortlessly. With Dropbox, team members can work together like they're sitting right next to each other — even when they're halfway around the world.",
        price: 'From CA$4.10',
        period: 'user/month',
    },

]

